groups:
  - name: api-alerts
    rules:
      - alert: HighErrorRate
        expr: |
          (sum(rate(http_requests_total{status=~"5.."}[5m])) /
           sum(rate(http_requests_total[5m]))) > 0.05
        for: 10m
        labels: { severity: warning }
        annotations:
          summary: "5xx error rate > 5% (5m)"

      - alert: HighP95Latency
        expr: |
          histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.8
        for: 10m
        labels: { severity: warning }
        annotations:
          summary: "p95 latency > 800ms (5m)"

      - alert: Low304Ratio
        expr: |
          (sum(rate(http_requests_total{status="304"}[10m])) /
           sum(rate(http_requests_total[10m]))) < 0.02
        for: 20m
        labels: { severity: info }
        annotations:
          summary: "304 ratio too low (check cache)"

      - alert: RateLimitDropsSpike
        expr: increase(rate_limit_drops_total[5m]) > 50
        for: 5m
        labels: { severity: warning }
        annotations:
          summary: "Rate-limit drops spiking"
