services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  api:
    build: { context: ../go-api }
    env_file: ../go-api/.env
    ports: ["8080:8080"]
    depends_on:
      postgres: { condition: service_healthy }
    read_only: true
    tmpfs: ["/tmp:rw,noexec,nosuid,size=64m"]
    security_opt: ["no-new-privileges:true"]
    cap_drop: ["ALL"]
    mem_limit: "256m"
    cpus: "0.50"
    restart: unless-stopped

  web:
    build: { context: ../webapp }
    env_file: ../webapp/.env
    ports: ["3000:80"]
    depends_on:
      api: { condition: service_started }
    read_only: true
    tmpfs: ["/var/cache/nginx:rw,noexec,nosuid,size=64m","/var/run:rw,noexec,nosuid,size=16m","/tmp:rw,noexec,nosuid,size=32m"]
    security_opt: ["no-new-privileges:true"]
    cap_drop: ["ALL"]
    mem_limit: "128m"
    cpus: "0.50"
    restart: unless-stopped

volumes:
  pg-data:
