global:
  scrape_interval: 15s
scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

        rule_files:
          - /etc/prometheus/alerts.yml
