\connect appdb
CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION app;

CREATE TABLE IF NOT EXISTS app.items (
                                         id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name       VARCHAR(100) NOT NULL,
    price      NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

