-- 0002_create_items.sql
-- +goose Up
CREATE TABLE IF NOT EXISTS app.items(
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(100) NOT NULL,
    price NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
    );
-- +goose Down
DROP TABLE IF EXISTS app.items;
