-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS app.users (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         email TEXT NOT NULL UNIQUE,
                                         password_hash TEXT NOT NULL,
                                         role TEXT NOT NULL DEFAULT 'user',
                                         created_at timestamptz NOT NULL DEFAULT now()
    );

-- +goose Down
DROP TABLE IF EXISTS app.users;
